# Generated by Django 5.1.15 on 2026-07-15 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0007_rentalapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("landlord", "Landlord"),
                            ("artisan", "Artisan"),
                            ("identity", "Identity"),
                            ("property_ownership", "Property Ownership"),
                            ("property_listing", "Property Listing"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_more_information", "Needs More Information"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="not_submitted",
                        max_length=32,
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=255)),
                (
                    "cac_registration_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("trade_category", models.CharField(blank=True, max_length=100)),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("contact_address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("review_notes", models.TextField(blank=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=64)),
                ("file", models.FileField(upload_to="verification/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveIntegerField()),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reviewed_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_more_information", "Needs More Information"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "verification_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="trust.verificationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_more_information", "Needs More Information"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="not_submitted",
                        max_length=32,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("verified_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="properties.property",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_property_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_property_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspection_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trust.verificationdocument",
                    ),
                ),
                (
                    "location_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trust.verificationdocument",
                    ),
                ),
                (
                    "ownership_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trust.verificationdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "status"],
                        name="trust_prope_propert_3b973a_idx",
                    ),
                    models.Index(
                        fields=["reviewer", "status"],
                        name="trust_prope_reviewe_024020_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "pending",
                                    "under_review",
                                    "needs_more_information",
                                    "approved",
                                    "suspended",
                                ],
                            )
                        ),
                        fields=("property",),
                        name="uniq_active_verification_per_property",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["verification_type", "status"],
                name="trust_verif_verific_bfe4af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["reviewer", "status"], name="trust_verif_reviewe_d5dc25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["user", "status"], name="trust_verif_user_id_683495_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "under_review",
                            "needs_more_information",
                            "approved",
                            "suspended",
                        ],
                    )
                ),
                fields=("user", "verification_type"),
                name="uniq_active_verification_per_user_type",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(
                fields=["verification_request", "document_type"],
                name="trust_verif_verific_273e8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(
                fields=["checksum"], name="trust_verif_checksu_61eee3_idx"
            ),
        ),
    ]
