# Generated by Django 5.1.15 on 2026-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationdocument",
            name="file",
            field=models.FileField(
                storage="verification", upload_to="verification/%Y/%m/"
            ),
        ),
    ]
