# Generated by Django 5.1.15 on 2026-07-16 02:01

import apps.trust.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0002_alter_verificationdocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationdocument",
            name="file",
            field=models.FileField(
                storage=apps.trust.storage.get_verification_storage,
                upload_to="verification/%Y/%m/",
            ),
        ),
    ]
