# Generated by Django 5.1.15 on 2026-07-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0003_alter_verificationdocument_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationdocument",
            name="property_verification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="trust.propertyverification",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocument",
            name="verification_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="trust.verificationrequest",
            ),
        ),
    ]
