# Generated by Django 5.1.15 on 2026-07-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0004_verificationdocument_property_verification_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="verificationdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("property_verification__isnull", True),
                        ("verification_request__isnull", False),
                    ),
                    models.Q(
                        ("property_verification__isnull", False),
                        ("verification_request__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="document_has_exactly_one_parent",
            ),
        ),
    ]
