# Generated by Django 5.1.15 on 2026-06-16 20:14

from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_5ca9a9_idx',
            old_name='accounts_au_action_7061b2_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_entity__473722_idx',
            old_name='accounts_au_entity__6c8b39_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_actor_i_670b11_idx',
            old_name='accounts_au_actor_i_4512b3_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_a7d3a8_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_phone_n_613c4a_idx',
            old_name='accounts_us_phone_n_b58175_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_is_acti_c45a13_idx',
            old_name='accounts_us_is_acti_142586_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='accounts_us_user_id_643173_idx',
            old_name='accounts_us_user_id_daf398_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='accounts_us_role_id_11f78a_idx',
            old_name='accounts_us_role_id_095d3b_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='accounts_us_created_cf74dd_idx',
            old_name='accounts_us_created_18dc2c_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
