# Generated by Django 5.1.15 on 2026-07-31 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('business_name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('biography', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=120)),
                ('lga', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=160)),
                ('private_address', models.TextField(blank=True)),
                ('display_location', models.CharField(blank=True, max_length=220)),
                ('verification_snapshot', models.JSONField(blank=True, default=dict)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_jobs_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=120)),
                ('lga', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=160)),
                ('service_radius_km', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['state', 'city', 'lga', 'neighborhood'],
            },
        ),
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('requires_certification', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='services.tradecategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill_level', models.CharField(choices=[('apprentice', 'Apprentice'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='services.serviceprovider')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_trades', to='services.tradecategory')),
            ],
            options={
                'ordering': ['-is_primary', 'category__name'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['slug'], name='services_se_slug_ed75bd_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['status', 'created_at'], name='services_se_status_f0ea62_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['provider_type', 'status'], name='services_se_provide_402656_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['state', 'city', 'status'], name='services_se_state_c00bce_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['lga', 'status'], name='services_se_lga_17d1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['average_rating'], name='services_se_average_bed5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['completed_jobs_count'], name='services_se_complet_37407d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['provider'], name='services_se_provide_d92274_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['state', 'city'], name='services_se_state_015d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['lga'], name='services_se_lga_ce924a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['neighborhood'], name='services_se_neighbo_87c5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='tradecategory',
            index=models.Index(fields=['slug'], name='services_tr_slug_d317d5_idx'),
        ),
        migrations.AddIndex(
            model_name='tradecategory',
            index=models.Index(fields=['parent', 'is_active', 'display_order'], name='services_tr_parent__a7c568_idx'),
        ),
        migrations.AddIndex(
            model_name='tradecategory',
            index=models.Index(fields=['name'], name='services_tr_name_d49ebe_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name'), name='unique_active_trade_category_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='providertrade',
            index=models.Index(fields=['provider', 'status'], name='services_pr_provide_1a7264_idx'),
        ),
        migrations.AddIndex(
            model_name='providertrade',
            index=models.Index(fields=['category', 'status'], name='services_pr_categor_f3024c_idx'),
        ),
        migrations.AddIndex(
            model_name='providertrade',
            index=models.Index(fields=['is_primary'], name='services_pr_is_prim_bc580e_idx'),
        ),
        migrations.AddConstraint(
            model_name='providertrade',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'category'), name='unique_active_provider_trade_category'),
        ),
        migrations.AddConstraint(
            model_name='providertrade',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('provider',), name='unique_primary_trade_per_provider'),
        ),
    ]
