# Generated by Django 5.1.15 on 2026-08-01 17:33

import apps.services.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_trade_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('image', models.ImageField(upload_to=apps.services.models.portfolio_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='servicearea',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='more_info_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='suspended_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('needs_more_information', 'Needs More Information'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['provider', 'is_primary'], name='services_se_provide_464aa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicearea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('provider',), name='unique_primary_service_area_per_provider'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_images', to='services.tradecategory'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='services.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['provider', 'display_order'], name='services_po_provide_6eda41_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['provider', 'is_cover'], name='services_po_provide_ae2354_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['provider', 'status'], name='services_po_provide_e80fdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioimage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_cover', True)), fields=('provider',), name='unique_cover_portfolio_image_per_provider'),
        ),
    ]
