# Generated by Django 5.1.15 on 2026-08-01 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_portfolioimage_servicearea_is_primary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('project_title', models.CharField(max_length=180)),
                ('project_description', models.TextField()),
                ('budget_range', models.CharField(blank=True, max_length=120)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='phone', max_length=20)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('property_address', models.TextField(blank=True)),
                ('state', models.CharField(max_length=80)),
                ('lga', models.CharField(blank=True, max_length=120)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed'), ('responded', 'Responded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='services.serviceprovider')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='services.tradecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status', 'created_at'], name='services_qu_provide_8a2675_idx'), models.Index(fields=['customer', 'created_at'], name='services_qu_custome_09ee60_idx'), models.Index(fields=['state', 'lga'], name='services_qu_state_dd36ce_idx')],
            },
        ),
    ]
