# Generated by Django 5.1.15 on 2026-08-03 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='average_communication_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='average_punctuality_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='average_quality_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='average_value_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='published_review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='recommendation_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('comment', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('punctuality_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('value_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('flagged', 'Flagged'), ('hidden', 'Hidden'), ('disputed', 'Disputed'), ('removed', 'Removed')], db_index=True, default='pending', max_length=20)),
                ('provider_response', models.TextField(blank=True)),
                ('provider_responded_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('creation_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='services.servicebooking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReviewFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abusive', 'Abusive'), ('false_information', 'False Information'), ('privacy_concern', 'Privacy Concern'), ('conflict_of_interest', 'Conflict of Interest'), ('other', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags', to='services.servicereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_review_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='services_se_provide_e487d5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['customer', 'created_at'], name='services_se_custome_9f0412_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['rating', 'created_at'], name='services_se_rating_550fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['published_at'], name='services_se_publish_605856_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='service_review_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.CheckConstraint(condition=models.Q(('quality_rating__isnull', True), models.Q(('quality_rating__gte', 1), ('quality_rating__lte', 5)), _connector='OR'), name='service_review_quality_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.CheckConstraint(condition=models.Q(('punctuality_rating__isnull', True), models.Q(('punctuality_rating__gte', 1), ('punctuality_rating__lte', 5)), _connector='OR'), name='service_review_punctuality_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.CheckConstraint(condition=models.Q(('communication_rating__isnull', True), models.Q(('communication_rating__gte', 1), ('communication_rating__lte', 5)), _connector='OR'), name='service_review_communication_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.CheckConstraint(condition=models.Q(('value_rating__isnull', True), models.Q(('value_rating__gte', 1), ('value_rating__lte', 5)), _connector='OR'), name='service_review_value_rating_between_1_and_5'),
        ),
        migrations.AddIndex(
            model_name='servicereviewflag',
            index=models.Index(fields=['review', 'reason', 'created_at'], name='services_se_review__0d70c1_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereviewflag',
            index=models.Index(fields=['user', 'created_at'], name='services_se_user_id_89c701_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicereviewflag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('review', 'user'), name='unique_active_service_review_flag_per_user'),
        ),
    ]
