# Generated by Django 5.1.15 on 2026-08-05 10:15

import apps.services.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_serviceprovider_average_communication_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('appeal_type', models.CharField(choices=[('warning', 'Warning Appeal'), ('suspension', 'Suspension Appeal')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reopened', 'Reopened'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('complaint_type', models.CharField(choices=[('customer', 'Customer Complaint'), ('provider', 'Provider Complaint')], max_length=20)),
                ('category', models.CharField(choices=[('provider_conduct', 'Provider Conduct'), ('customer_conduct', 'Customer Conduct'), ('review_abuse', 'Review Abuse'), ('safety', 'Safety'), ('fraud', 'Fraud'), ('service_quality', 'Service Quality'), ('other', 'Other')], default='other', max_length=40)),
                ('subject', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('awaiting_customer', 'Awaiting Customer'), ('awaiting_provider', 'Awaiting Provider'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=24)),
                ('resolution_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceComplaintEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(upload_to=apps.services.models.complaint_evidence_upload_to)),
                ('caption', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='appeal_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reopened', 'Reopened'), ('closed', 'Closed')], max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='last_warning_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='suspension_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='suspension_type',
            field=models.CharField(blank=True, choices=[('warning', 'Warning'), ('temporary', 'Temporary Suspension'), ('permanent', 'Permanent Suspension')], max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='warning_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['suspension_type', 'suspension_expires_at'], name='services_se_suspens_210ded_idx'),
        ),
        migrations.AddField(
            model_name='providerappeal',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_service_provider_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerappeal',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='providerappeal',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_provider_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecomplaint',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecomplaint',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='services.servicebooking'),
        ),
        migrations.AddField(
            model_name='servicecomplaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecomplaint',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicecomplaint',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='services.quoterequest'),
        ),
        migrations.AddField(
            model_name='servicecomplaint',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='services.servicereview'),
        ),
        migrations.AddField(
            model_name='servicecomplaintevidence',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='services.servicecomplaint'),
        ),
        migrations.AddField(
            model_name='servicecomplaintevidence',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_complaint_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='providerappeal',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='services_pr_provide_f5bd04_idx'),
        ),
        migrations.AddIndex(
            model_name='providerappeal',
            index=models.Index(fields=['submitted_by', 'created_at'], name='services_pr_submitt_c5fff7_idx'),
        ),
        migrations.AddIndex(
            model_name='providerappeal',
            index=models.Index(fields=['appeal_type', 'status'], name='services_pr_appeal__cfce1e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomplaint',
            index=models.Index(fields=['complainant', 'created_at'], name='services_se_complai_f3fd82_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomplaint',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='services_se_provide_e15fca_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomplaint',
            index=models.Index(fields=['status', 'created_at'], name='services_se_status_48eeed_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomplaint',
            index=models.Index(fields=['category', 'status'], name='services_se_categor_13bf6e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomplaint',
            index=models.Index(fields=['assigned_admin', 'status'], name='services_se_assigne_7020ff_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomplaintevidence',
            index=models.Index(fields=['complaint', 'created_at'], name='services_se_complai_6e0161_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomplaintevidence',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='services_se_uploade_249254_idx'),
        ),
    ]
