# Generated by Django 5.1.15 on 2026-06-18 15:25

import apps.properties.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.properties.models.property_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['property', 'display_order'], name='properties__propert_020873_idx'), models.Index(fields=['property', 'is_cover'], name='properties__propert_c2e6b6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('property',), name='unique_cover_image_per_property')],
            },
        ),
    ]
