# Generated by Django 5.1.15 on 2026-07-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_listing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inquiry_type', models.CharField(choices=[('rent', 'Rent'), ('purchase', 'Purchase'), ('apartment_share', 'Apartment Share')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing_scheduled', 'Viewing Scheduled'), ('negotiating', 'Negotiating'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=32)),
                ('internal_notes', models.TextField(blank=True)),
                ('interested_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_inquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='properties.property')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_property_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['interested_user', 'status', 'created_at'], name='properties__interes_0adb85_idx'), models.Index(fields=['property_owner', 'status', 'created_at'], name='properties__propert_35d5c8_idx'), models.Index(fields=['property', 'status'], name='properties__propert_8d7fce_idx'), models.Index(fields=['status', 'created_at'], name='properties__status_dd4982_idx'), models.Index(fields=['inquiry_type'], name='properties__inquiry_0fe975_idx')],
            },
        ),
    ]
