# Generated by Django 5.1.15 on 2026-07-09 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('viewing_type', models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual')], max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=240)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('rescheduled', 'Rescheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewings', to='properties.inquiry')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewings', to='properties.property')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_viewing_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewing_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'status', 'created_at'], name='properties__request_33b8a6_idx'), models.Index(fields=['property_owner', 'status', 'created_at'], name='properties__propert_77cffa_idx'), models.Index(fields=['property', 'status'], name='properties__propert_81117f_idx'), models.Index(fields=['inquiry', 'status'], name='properties__inquiry_be5521_idx'), models.Index(fields=['preferred_date', 'preferred_time'], name='properties__preferr_16cb67_idx')],
            },
        ),
    ]
