# Generated by Django 5.1.15 on 2026-07-09 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_viewing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('employment_status', models.CharField(max_length=80)),
                ('employer_name', models.CharField(blank=True, max_length=160)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('move_in_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=32)),
                ('owner_notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_applications', to='properties.inquiry')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='properties.property')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_rental_applications', to=settings.AUTH_USER_MODEL)),
                ('viewing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_applications', to='properties.viewing')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant', 'status', 'created_at'], name='properties__applica_863a6b_idx'), models.Index(fields=['property_owner', 'status', 'created_at'], name='properties__propert_fd8e73_idx'), models.Index(fields=['property', 'status'], name='properties__propert_172ad8_idx'), models.Index(fields=['inquiry', 'status'], name='properties__inquiry_329327_idx'), models.Index(fields=['viewing', 'status'], name='properties__viewing_b169d9_idx'), models.Index(fields=['move_in_date'], name='properties__move_in_93b3fb_idx')],
            },
        ),
    ]
