# Generated by Django 5.1.15 on 2026-07-29 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rentalapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='display_location',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='property',
            name='geocoding_status',
            field=models.CharField(choices=[('not_geocoded', 'Not Geocoded'), ('pending', 'Pending'), ('geocoded', 'Geocoded'), ('failed', 'Failed'), ('manual', 'Manual')], default='not_geocoded', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lga',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='location_precision',
            field=models.CharField(choices=[('exact', 'Exact'), ('neighborhood', 'Neighborhood'), ('city', 'City'), ('hidden', 'Hidden')], default='neighborhood', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='property',
            name='show_exact_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state', 'city', 'status'], name='properties__state_fb31f1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['lga', 'status'], name='properties__lga_bcd943_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['neighborhood', 'status'], name='properties__neighbo_3b25d4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties__latitud_6eb2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location_precision', 'status'], name='properties__locatio_55c29b_idx'),
        ),
    ]
