# Generated by Django 5.1.15 on 2026-08-11 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_display_location_property_geocoding_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('relationship_type', models.CharField(choices=[('agent', 'Agent'), ('property_manager', 'Property Manager'), ('caretaker', 'Caretaker'), ('project_manager', 'Project Manager'), ('authorized_representative', 'Authorized Representative')], default='authorized_representative', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_property_assignments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'status'], name='properties__propert_a180b3_idx'), models.Index(fields=['user', 'status'], name='properties__user_id_5bcf24_idx'), models.Index(fields=['relationship_type', 'status'], name='properties__relatio_1459b4_idx'), models.Index(fields=['expires_at'], name='properties__expires_b70ef3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('property', 'user', 'relationship_type'), name='unique_live_property_assignment_type_per_user')],
            },
        ),
    ]
