# Generated by Django 5.1.15 on 2026-08-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_display_location_property_geocoding_status_and_more'),
        ('properties', '0009_leadactivity'),
    ]

    operations = [
    ]
