# Generated by Django 5.1.15 on 2026-08-12 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('follow_up_scheduled', 'Follow-up Scheduled'), ('follow_up_completed', 'Follow-up Completed'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='closed_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='conversion_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='follow_up_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='pipeline_stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('viewing_scheduled', 'Viewing Scheduled'), ('application_started', 'Application Started'), ('application_submitted', 'Application Submitted'), ('negotiating', 'Negotiating'), ('converted', 'Converted'), ('closed_lost', 'Closed Lost')], default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['pipeline_stage', 'created_at'], name='properties__pipelin_12f455_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['assigned_to', 'pipeline_stage'], name='properties__assigne_b080ff_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['priority'], name='properties__priorit_90aae9_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['next_follow_up_at'], name='properties__next_fo_f88002_idx'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='properties.inquiry'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['inquiry', 'created_at'], name='properties__inquiry_2f374b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['inquiry', 'activity_type'], name='properties__inquiry_0ceda4_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['scheduled_for'], name='properties__schedul_573f28_idx'),
        ),
    ]
