# Generated by Django 5.1.15 on 2026-08-11 17:44

import apps.construction.models
import apps.construction.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('properties', '0009_propertyassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('awaiting_inspection', 'Awaiting Inspection'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='not_started', max_length=24)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requires_inspection', models.BooleanField(default=False)),
                ('blocking', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_milestones', to='construction.constructionmilestone')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('new_build', 'New Build'), ('renovation', 'Renovation'), ('extension', 'Extension'), ('remodel', 'Remodel'), ('repair', 'Repair'), ('commercial_development', 'Commercial Development'), ('residential_development', 'Residential Development'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], default='renovation', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('owner_only', 'Owner Only'), ('stakeholders', 'Stakeholders'), ('admin_only', 'Admin Only')], default='stakeholders', max_length=24)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contractor_name_or_reference', models.CharField(blank=True, max_length=180)),
                ('estimated_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_construction_projects', to=settings.AUTH_USER_MODEL)),
                ('current_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='construction.constructionmilestone')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_construction_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_construction_projects', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_projects', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProgressUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('work_completed', models.TextField(blank=True)),
                ('current_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issues', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_updates', to='construction.constructionmilestone')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_construction_progress_updates', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_progress_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='construction.constructionproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='construction.constructionproject'),
        ),
        migrations.CreateModel(
            name='ConstructionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], default='photo', max_length=16)),
                ('file', models.FileField(storage=apps.construction.storage.get_construction_evidence_storage, upload_to=apps.construction.models.construction_evidence_upload_to)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=100)),
                ('visibility', models.CharField(choices=[('project_stakeholders', 'Project Stakeholders'), ('owner_and_admins', 'Owner and Admins'), ('admins_only', 'Admins Only')], default='project_stakeholders', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_evidence_uploads', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='construction.constructionmilestone')),
                ('progress_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='construction.constructionprogressupdate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='construction.constructionproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_internal', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='construction.constructionmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='construction.constructionproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stakeholder_role', models.CharField(choices=[('owner', 'Owner'), ('investor', 'Investor'), ('project_manager', 'Project Manager'), ('contractor', 'Contractor'), ('inspector', 'Inspector'), ('viewer', 'Viewer')], default='viewer', max_length=24)),
                ('access_level', models.CharField(choices=[('read_only', 'Read Only'), ('commenter', 'Commenter'), ('operator', 'Operator'), ('manager', 'Manager'), ('owner', 'Owner')], default='read_only', max_length=16)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='invited', max_length=16)),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_construction_stakeholders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='construction.constructionproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_stakeholderships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stakeholder_role', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionMilestoneInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('inspection_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_milestone_links', to='inspections.inspectionrequest')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_links', to='construction.constructionmilestone')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_milestone_inspection_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['milestone', 'created_at'], name='constructio_milesto_283b06_idx'), models.Index(fields=['inspection_request', 'created_at'], name='constructio_inspect_7beeec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['property', 'status'], name='constructio_propert_1df999_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='constructio_owner_i_99919b_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['project_manager', 'status'], name='constructio_project_b53bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['status', 'planned_end_date'], name='constructio_status_ff5644_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionproject',
            index=models.Index(fields=['slug'], name='constructio_slug_898ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionprogressupdate',
            index=models.Index(fields=['project', 'status', 'created_at'], name='constructio_project_22da0a_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionprogressupdate',
            index=models.Index(fields=['milestone', 'status', 'created_at'], name='constructio_milesto_826341_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionprogressupdate',
            index=models.Index(fields=['submitted_by', 'created_at'], name='constructio_submitt_e13514_idx'),
        ),
        migrations.AddConstraint(
            model_name='constructionprogressupdate',
            constraint=models.CheckConstraint(condition=models.Q(('current_progress__gte', 0), ('current_progress__lte', 100)), name='construction_update_progress_between_0_and_100'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['project', 'sequence'], name='constructio_project_d4d9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['project', 'status'], name='constructio_project_461698_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['requires_inspection', 'status'], name='constructio_require_605301_idx'),
        ),
        migrations.AddConstraint(
            model_name='constructionmilestone',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'sequence'), name='unique_live_construction_milestone_sequence'),
        ),
        migrations.AddConstraint(
            model_name='constructionmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='construction_milestone_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='constructionmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='construction_milestone_progress_between_0_and_100'),
        ),
        migrations.AddIndex(
            model_name='constructionevidence',
            index=models.Index(fields=['project', 'status', 'created_at'], name='constructio_project_f3d612_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionevidence',
            index=models.Index(fields=['milestone', 'created_at'], name='constructio_milesto_1294e8_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionevidence',
            index=models.Index(fields=['progress_update', 'created_at'], name='constructio_progres_032a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionevidence',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='constructio_uploade_0062b2_idx'),
        ),
        migrations.AddIndex(
            model_name='constructiontimelineevent',
            index=models.Index(fields=['project', 'created_at'], name='constructio_project_61a0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='constructiontimelineevent',
            index=models.Index(fields=['milestone', 'created_at'], name='constructio_milesto_95c1af_idx'),
        ),
        migrations.AddIndex(
            model_name='constructiontimelineevent',
            index=models.Index(fields=['event_type'], name='constructio_event_t_3dbc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='constructiontimelineevent',
            index=models.Index(fields=['is_internal'], name='constructio_is_inte_70feff_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstakeholder',
            index=models.Index(fields=['project', 'status'], name='constructio_project_39cffb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstakeholder',
            index=models.Index(fields=['user', 'status'], name='constructio_user_id_ac15b4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstakeholder',
            index=models.Index(fields=['stakeholder_role', 'access_level'], name='constructio_stakeho_4e6329_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectstakeholder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'user'), name='unique_live_project_stakeholder_per_user'),
        ),
    ]
