# Generated by Django 5.1.15 on 2026-08-05 16:12

import apps.inspections.models
import apps.inspections.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0008_property_display_location_property_geocoding_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inspection_type', models.CharField(choices=[('general', 'General'), ('pre_purchase', 'Pre Purchase'), ('pre_rental', 'Pre Rental'), ('structural', 'Structural'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('construction_progress', 'Construction Progress'), ('land_verification', 'Land Verification'), ('commercial', 'Commercial'), ('other', 'Other')], default='general', max_length=40)),
                ('purpose', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('alternative_date', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(max_length=40)),
                ('contact_email', models.EmailField(max_length=254)),
                ('access_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('needs_more_information', 'Needs More Information'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('report_submitted', 'Report Submitted'), ('report_under_review', 'Report Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='requested', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('access_instructions', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspection_operations', to=settings.AUTH_USER_MODEL)),
                ('assigned_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspection_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_requests', to='properties.property')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('summary', models.TextField()),
                ('overall_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical'), ('not_assessed', 'Not Assessed')], default='not_assessed', max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical'), ('not_assessed', 'Not Assessed')], default='not_assessed', max_length=20)),
                ('structural_notes', models.TextField(blank=True)),
                ('electrical_notes', models.TextField(blank=True)),
                ('plumbing_notes', models.TextField(blank=True)),
                ('roofing_notes', models.TextField(blank=True)),
                ('security_notes', models.TextField(blank=True)),
                ('environment_notes', models.TextField(blank=True)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('estimated_repair_notes', models.TextField(blank=True)),
                ('report_document', models.FileField(blank=True, null=True, storage=apps.inspections.storage.get_inspection_report_storage, upload_to=apps.inspections.models.inspection_report_upload_to)),
                ('report_document_mime_type', models.CharField(blank=True, max_length=100)),
                ('report_document_file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('inspection_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='inspections.inspectionrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('reassigned', 'Reassigned'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_assignments', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_assignments', to=settings.AUTH_USER_MODEL)),
                ('reassigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments', to='inspections.inspectionassignment')),
                ('inspection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inspections.inspectionrequest')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_internal', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('inspection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='inspections.inspectionrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('display_name', models.CharField(max_length=160)),
                ('professional_title', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('inspection_types', models.JSONField(blank=True, default=list)),
                ('service_areas', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('average_rating_placeholder', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_inspections', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inspector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyWalkthrough',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(storage=apps.inspections.storage.get_walkthrough_storage, upload_to=apps.inspections.models.walkthrough_upload_to)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=apps.inspections.storage.get_walkthrough_storage, upload_to=apps.inspections.models.walkthrough_thumbnail_upload_to)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploading', 'Uploading'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden'), ('archived', 'Archived'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('moderation_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthroughs', to='properties.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_property_walkthroughs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_walkthroughs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('voice_note', 'Voice Note'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(storage=apps.inspections.storage.get_inspection_evidence_storage, upload_to=apps.inspections.models.inspection_evidence_upload_to)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('category', models.CharField(choices=[('structural', 'Structural'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('roofing', 'Roofing'), ('security', 'Security'), ('environment', 'Environment'), ('interior', 'Interior'), ('exterior', 'Exterior'), ('land', 'Land'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=32)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('private_internal', 'Private Internal'), ('requester_visible', 'Requester Visible'), ('property_owner_visible', 'Property Owner Visible'), ('admin_only', 'Admin Only')], default='requester_visible', max_length=32)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_evidence_uploads', to=settings.AUTH_USER_MODEL)),
                ('inspection_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='inspections.inspectionreport')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['inspection_report', 'category', 'display_order'], name='inspections_inspect_63904a_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='inspections_uploade_447a98_idx'), models.Index(fields=['visibility'], name='inspections_visibil_e878c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['requester', 'status', 'created_at'], name='inspections_request_ac8924_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['property', 'status', 'created_at'], name='inspections_propert_c567ef_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['assigned_inspector', 'status', 'scheduled_for'], name='inspections_assigne_e01dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='inspections_status_0362e9_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['inspection_type', 'status'], name='inspections_inspect_329d97_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['scheduled_for'], name='inspections_schedul_4c02df_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['requested', 'under_review', 'needs_more_information', 'approved', 'assigned', 'scheduled', 'in_progress', 'report_submitted', 'report_under_review'])), fields=('property', 'requester'), name='unique_active_inspection_request_per_user_property'),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['inspector', 'status', 'created_at'], name='inspections_inspect_1e2ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['status', 'created_at'], name='inspections_status_a21721_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionassignment',
            index=models.Index(fields=['inspection_request', 'status'], name='inspections_inspect_f2c30f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionassignment',
            index=models.Index(fields=['inspector', 'status', 'assigned_at'], name='inspections_inspect_c04acd_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontimelineevent',
            index=models.Index(fields=['inspection_request', 'created_at'], name='inspections_inspect_452e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontimelineevent',
            index=models.Index(fields=['event_type'], name='inspections_event_t_e03be6_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontimelineevent',
            index=models.Index(fields=['is_internal'], name='inspections_is_inte_8af91d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectorprofile',
            index=models.Index(fields=['active', 'verification_status', 'availability_status'], name='inspections_active_8a8b97_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectorprofile',
            index=models.Index(fields=['display_name'], name='inspections_display_8616d4_idx'),
        ),
        migrations.AddIndex(
            model_name='propertywalkthrough',
            index=models.Index(fields=['property', 'status', 'display_order'], name='inspections_propert_210370_idx'),
        ),
        migrations.AddIndex(
            model_name='propertywalkthrough',
            index=models.Index(fields=['uploaded_by', 'status', 'created_at'], name='inspections_uploade_1e14e6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertywalkthrough',
            index=models.Index(fields=['status', 'created_at'], name='inspections_status_733932_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertywalkthrough',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_featured', True)), fields=('property',), name='unique_featured_walkthrough_per_property'),
        ),
    ]
