# Generated by Django 5.1.15 on 2026-08-13 15:08

import apps.payments.storage
import apps.payments.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0010_leadactivity_inquiry_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='draft', max_length=32)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='properties.rentalapplication')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_owner', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proof_uploaded', 'Proof Uploaded'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='payments.transaction')),
            ],
            options={
                'ordering': ['transaction', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=32)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='payments.paymentmilestone')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(storage=apps.payments.storage.get_payment_proof_storage, upload_to='payment-proofs/%Y/%m/', validators=[apps.payments.validators.validate_payment_proof])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='payments.paymentmilestone')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['milestone', 'created_at'], name='payments_pa_milesto_896d26_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='payments_pa_uploade_d4c0f0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_claimed__gt', 0)), name='payment_proof_amount_claimed_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer', 'status', 'created_at'], name='payments_tr_buyer_i_4ccdeb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='payments_tr_owner_i_8cf926_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['property', 'status'], name='payments_tr_propert_a70c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['application', 'status'], name='payments_tr_applica_980c67_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('buyer', models.F('owner')), _negated=True), name='transaction_buyer_owner_different'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('application__isnull', False), ('deleted_at__isnull', True)), fields=('application',), name='unique_live_transaction_per_application'),
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['transaction', 'status'], name='payments_pa_transac_0d0126_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['transaction', 'order'], name='payments_pa_transac_e0d3f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_milestone_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['transaction', 'status', 'created_at'], name='payments_pa_transac_3f32cb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['opened_by', 'status', 'created_at'], name='payments_pa_opened__a156e3_idx'),
        ),
    ]
