# Generated by Django 5.1.15 on 2026-08-15 19:56

import apps.payments.models
import apps.payments.storage
import apps.payments.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_escrowprovider_escrowtransaction_escrowsettlement_and_more'),
        ('properties', '0010_leadactivity_inquiry_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], db_index=True, default='draft', max_length=32)),
                ('partner_type', models.CharField(choices=[('bank', 'Bank'), ('fintech', 'Fintech'), ('mortgage_bank', 'Mortgage Bank'), ('cooperative', 'Cooperative'), ('manual', 'Manual Partner')], default='manual', max_length=32)),
                ('integration_mode', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('hybrid', 'Hybrid')], default='manual', max_length=24)),
                ('supported_products', models.JSONField(blank=True, default=list)),
                ('supported_states', models.JSONField(blank=True, default=list)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('maximum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contact_policy', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'partner_type'], name='payments_fi_status_782b83_idx'), models.Index(fields=['integration_mode', 'status'], name='payments_fi_integra_d9b90e_idx'), models.Index(fields=['slug'], name='payments_fi_slug_ff58e3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('maximum_amount__gte', 0), ('minimum_amount__gte', 0)), name='financing_partner_amounts_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='FinancingProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('product_type', models.CharField(choices=[('rent_finance', 'Rent Finance'), ('mortgage', 'Mortgage')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='draft', max_length=24)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('minimum_tenor_months', models.PositiveSmallIntegerField(default=1)),
                ('maximum_tenor_months', models.PositiveSmallIntegerField(default=24)),
                ('requires_property', models.BooleanField(default=True)),
                ('requires_income_documents', models.BooleanField(default=True)),
                ('requires_identity_verification', models.BooleanField(default=True)),
                ('requires_bank_statement', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='payments.financingpartner')),
            ],
            options={
                'ordering': ['product_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancingDocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('document_type', models.CharField(choices=[('identity', 'Identity'), ('bank_statement', 'Bank Statement'), ('income_proof', 'Income Proof'), ('employment_letter', 'Employment Letter'), ('property_document', 'Property Document'), ('other', 'Other')], max_length=40)),
                ('required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('allowed_mime_types', models.JSONField(blank=True, default=list)),
                ('max_size_mb', models.PositiveSmallIntegerField(default=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='payments.financingproduct')),
            ],
            options={
                'ordering': ['product', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='FinancingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('application_reference', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('partner_review', 'Partner Review'), ('more_information_requested', 'More Information Requested'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=40)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('purpose', models.TextField()),
                ('preferred_tenor_months', models.PositiveSmallIntegerField()),
                ('employment_status', models.CharField(max_length=80)),
                ('monthly_income_band', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('consent_status', models.CharField(choices=[('not_granted', 'Not Granted'), ('granted', 'Granted'), ('revoked', 'Revoked')], db_index=True, default='not_granted', max_length=24)),
                ('applicant_message', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('partner_status', models.CharField(blank=True, max_length=80)),
                ('partner_reference', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('partner_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_applications', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financing_applications', to='properties.property')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_applications', to='payments.transaction')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='payments.financingpartner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='payments.financingproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancingTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('applicant', 'Applicant'), ('partner', 'Partner')], db_index=True, default='applicant', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='payments.financingapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancingConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(max_length=200)),
                ('accepted_terms_version', models.CharField(max_length=40)),
                ('consented_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_consents', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='payments.financingapplication')),
            ],
            options={
                'ordering': ['-consented_at'],
                'indexes': [models.Index(fields=['application', 'consented_at'], name='payments_fi_applica_a8148d_idx'), models.Index(fields=['applicant', 'consented_at'], name='payments_fi_applica_d4603d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('document_type', models.CharField(choices=[('identity', 'Identity'), ('bank_statement', 'Bank Statement'), ('income_proof', 'Income Proof'), ('employment_letter', 'Employment Letter'), ('property_document', 'Property Document'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(storage=apps.payments.storage.get_financing_document_storage, upload_to=apps.payments.models.financing_document_upload_to, validators=[apps.payments.validators.validate_financing_document])),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='uploaded', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.financingapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_financing_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'document_type', 'status'], name='payments_fi_applica_f16f57_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='payments_fi_uploade_a95c8b_idx'), models.Index(fields=['checksum'], name='payments_fi_checksu_bd064a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancingOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('offer_reference', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=24)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('tenor_months', models.PositiveSmallIntegerField()),
                ('interest_rate_display', models.CharField(blank=True, max_length=120)),
                ('fees_display', models.CharField(blank=True, max_length=200)),
                ('monthly_payment_display', models.CharField(blank=True, max_length=120)),
                ('partner_terms_summary', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='payments.financingapplication')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_offers', to='payments.financingpartner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'status', 'created_at'], name='payments_fi_applica_f38335_idx'), models.Index(fields=['partner', 'status'], name='payments_fi_partner_051530_idx'), models.Index(fields=['offer_reference'], name='payments_fi_offer_r_7b73f7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('partner', 'offer_reference'), name='unique_live_financing_offer_reference'), models.CheckConstraint(condition=models.Q(('approved_amount__gt', 0)), name='financing_offer_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='FinancingPartnerSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submission_reference', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_submissions', to='payments.financingapplication')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_submissions', to='payments.financingpartner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'status'], name='payments_fi_applica_ebc2c0_idx'), models.Index(fields=['partner', 'status', 'created_at'], name='payments_fi_partner_6feda0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('partner', 'submission_reference'), name='unique_live_financing_partner_submission_ref')],
            },
        ),
        migrations.AddIndex(
            model_name='financingproduct',
            index=models.Index(fields=['status', 'product_type'], name='payments_fi_status_556263_idx'),
        ),
        migrations.AddIndex(
            model_name='financingproduct',
            index=models.Index(fields=['partner', 'status'], name='payments_fi_partner_555610_idx'),
        ),
        migrations.AddIndex(
            model_name='financingproduct',
            index=models.Index(fields=['currency', 'status'], name='payments_fi_currenc_4cdbee_idx'),
        ),
        migrations.AddConstraint(
            model_name='financingproduct',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_amount__gte', models.F('minimum_amount')), ('minimum_amount__gt', 0)), name='financing_product_amount_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='financingproduct',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_tenor_months__gte', models.F('minimum_tenor_months'))), name='financing_product_tenor_range_valid'),
        ),
        migrations.AddIndex(
            model_name='financingdocumentrequirement',
            index=models.Index(fields=['product', 'required'], name='payments_fi_product_15491e_idx'),
        ),
        migrations.AddConstraint(
            model_name='financingdocumentrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('product', 'document_type'), name='unique_live_financing_requirement_per_type'),
        ),
        migrations.AddIndex(
            model_name='financingapplication',
            index=models.Index(fields=['applicant', 'status', 'created_at'], name='payments_fi_applica_ef4720_idx'),
        ),
        migrations.AddIndex(
            model_name='financingapplication',
            index=models.Index(fields=['partner', 'status', 'created_at'], name='payments_fi_partner_6a3c04_idx'),
        ),
        migrations.AddIndex(
            model_name='financingapplication',
            index=models.Index(fields=['product', 'status'], name='payments_fi_product_2ebbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='financingapplication',
            index=models.Index(fields=['property', 'status'], name='payments_fi_propert_4fe5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='financingapplication',
            index=models.Index(fields=['transaction', 'status'], name='payments_fi_transac_495f18_idx'),
        ),
        migrations.AddIndex(
            model_name='financingapplication',
            index=models.Index(fields=['state', 'city', 'status'], name='payments_fi_state_76e5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='financingapplication',
            index=models.Index(fields=['application_reference'], name='payments_fi_applica_4e22ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='financingapplication',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='financing_application_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financingapplication',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_tenor_months__gt', 0)), name='financing_application_tenor_positive'),
        ),
        migrations.AddIndex(
            model_name='financingtimelineevent',
            index=models.Index(fields=['application', 'visibility', 'created_at'], name='payments_fi_applica_e2eccc_idx'),
        ),
        migrations.AddIndex(
            model_name='financingtimelineevent',
            index=models.Index(fields=['event_type', 'created_at'], name='payments_fi_event_t_53dd99_idx'),
        ),
    ]
