# Generated by Django 5.1.15 on 2026-08-16 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_financingpartner_financingproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financingconsent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('revoked_at__isnull', True)), fields=('application', 'applicant', 'accepted_terms_version'), name='unique_active_financing_consent_per_terms'),
        ),
    ]
