# Generated by Django 5.1.15 on 2026-07-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconversation",
            name="total_input_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="total_output_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
