# Generated by Django 5.1.15 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_aiconversation_total_input_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiconversation",
            name="provider",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("demo", "Demo"),
                    ("anthropic", "Anthropic"),
                ],
                default="anthropic",
                max_length=30,
            ),
        ),
    ]
