# Generated by Django 5.1.15 on 2026-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_assigned', 'Lead Assigned'), ('lead_stage_changed', 'Lead Stage Changed'), ('follow_up_due', 'Follow-up Due'), ('new_message', 'New Message'), ('inquiry_created', 'Inquiry Created'), ('inquiry_status_changed', 'Inquiry Status Changed'), ('viewing_requested', 'Viewing Requested'), ('viewing_confirmed', 'Viewing Confirmed'), ('viewing_rescheduled', 'Viewing Rescheduled'), ('viewing_cancelled', 'Viewing Cancelled'), ('application_submitted', 'Application Submitted'), ('application_status_changed', 'Application Status Changed'), ('system', 'System')], max_length=40),
        ),
    ]
