# Generated by Django 5.1.15 on 2026-08-12 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('message.created', 'Message Created'), ('notification.created', 'Notification Created')], max_length=80)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at', 'id'], name='notificatio_thread__cf9902_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('thread', 'sender', 'client_message_id'), name='unique_message_client_id_per_sender_thread'),
        ),
        migrations.AddField(
            model_name='realtimeoutboxevent',
            name='conversation_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtime_outbox_events', to='notifications.conversationthread'),
        ),
        migrations.AddField(
            model_name='realtimeoutboxevent',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtime_outbox_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='realtimeoutboxevent',
            index=models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='notificatio_status_c3e3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeoutboxevent',
            index=models.Index(fields=['event_type', 'aggregate_id'], name='notificatio_event_t_80d1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeoutboxevent',
            index=models.Index(fields=['recipient_user', 'status'], name='notificatio_recipie_8229fe_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeoutboxevent',
            index=models.Index(fields=['conversation_thread', 'status'], name='notificatio_convers_ecb430_idx'),
        ),
        migrations.AddConstraint(
            model_name='realtimeoutboxevent',
            constraint=models.UniqueConstraint(fields=('event_type', 'aggregate_id'), name='unique_realtime_outbox_event_per_aggregate'),
        ),
    ]
