# Generated by Django 5.1.15 on 2026-08-12 20:15

from django.conf import settings
from django.db import migrations, models


def backfill_thread_sequences(apps, schema_editor):
    message_model = apps.get_model("notifications", "Message")
    thread_ids = (
        message_model.objects.order_by()
        .values_list("thread_id", flat=True)
        .distinct()
    )
    for thread_id in thread_ids:
        messages = message_model.objects.filter(thread_id=thread_id).order_by("created_at", "id")
        for index, message in enumerate(messages, start=1):
            message_model.objects.filter(id=message.id).update(thread_sequence=index)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_realtimeoutboxevent_message_client_message_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'thread_sequence'], name='notificatio_thread__cca2fc_idx'),
        ),
        migrations.RunPython(backfill_thread_sequences, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('thread_sequence__isnull', False)), fields=('thread', 'thread_sequence'), name='unique_message_sequence_per_thread'),
        ),
    ]
